// <auto-generated />
using System;
using Atividade1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atividade1.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Atividade1.Agencia", b =>
                {
                    b.Property<int>("IdAgencia")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BancoIdBanco");

                    b.HasKey("IdAgencia");

                    b.HasIndex("BancoIdBanco");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("Atividade1.Banco", b =>
                {
                    b.Property<int>("IdBanco")
                        .ValueGeneratedOnAdd();

                    b.HasKey("IdBanco");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("Atividade1.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Atividade1.ContaCorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgenciaIdAgencia");

                    b.Property<decimal>("Saldo");

                    b.Property<string>("Titular");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaIdAgencia");

                    b.ToTable("ContasCorrentes");
                });

            modelBuilder.Entity("Atividade1.ContaPoupanca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgenciaIdAgencia");

                    b.Property<DateTime>("DataAniversario");

                    b.Property<decimal>("Juros");

                    b.Property<decimal>("Saldo");

                    b.Property<string>("Titular");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaIdAgencia");

                    b.ToTable("ContasPoupanca");
                });

            modelBuilder.Entity("Atividade1.Solicitacao", b =>
                {
                    b.Property<int>("IdSolicitacao")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgenciaIdAgencia");

                    b.HasKey("IdSolicitacao");

                    b.HasIndex("AgenciaIdAgencia");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("Atividade1.Agencia", b =>
                {
                    b.HasOne("Atividade1.Banco")
                        .WithMany("Agencias")
                        .HasForeignKey("BancoIdBanco");
                });

            modelBuilder.Entity("Atividade1.ContaCorrente", b =>
                {
                    b.HasOne("Atividade1.Agencia")
                        .WithMany("ContaCorrentes")
                        .HasForeignKey("AgenciaIdAgencia");
                });

            modelBuilder.Entity("Atividade1.ContaPoupanca", b =>
                {
                    b.HasOne("Atividade1.Agencia")
                        .WithMany("ContaPoupancas")
                        .HasForeignKey("AgenciaIdAgencia");
                });

            modelBuilder.Entity("Atividade1.Solicitacao", b =>
                {
                    b.HasOne("Atividade1.Agencia")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("AgenciaIdAgencia");
                });
#pragma warning restore 612, 618
        }
    }
}
